// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9Uh5lG60kf6qTxdzXvBuWWbc-5S4-UpE',
    appId: '1:692847091941:web:1e289faf0c136beed2b40c',
    messagingSenderId: '692847091941',
    projectId: 'beinghuman-79d2e',
    authDomain: 'beinghuman-79d2e.firebaseapp.com',
    storageBucket: 'beinghuman-79d2e.appspot.com',
    measurementId: 'G-W12JE7TCBV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKvf_PEAxdPwDSIGpGEWsCgIs8wquesjQ',
    appId: '1:692847091941:android:cc9842c6a6ebe8bcd2b40c',
    messagingSenderId: '692847091941',
    projectId: 'beinghuman-79d2e',
    storageBucket: 'beinghuman-79d2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJhl7_CCHubLL8hHsEUbxWGaKuPZLrWTA',
    appId: '1:692847091941:ios:b2e26f7697c1f7bfd2b40c',
    messagingSenderId: '692847091941',
    projectId: 'beinghuman-79d2e',
    storageBucket: 'beinghuman-79d2e.appspot.com',
    androidClientId: '692847091941-2q8dqnrsks69up8d8mmb2fkpqfvuprei.apps.googleusercontent.com',
    iosClientId: '692847091941-0tc61necjb59fm8ejnbp0hr3r6it0lnq.apps.googleusercontent.com',
    iosBundleId: 'com.example.beinghuman',
  );
}
